#!/bin/bash
set +e

gsettings set org.gnome.desktop.wm.preferences theme "Nordic"
gsettings set org.gnome.desktop.interface gtk-theme "Nordic"
gsettings set org.gnome.desktop.interface icon-theme "Flatery-Dark"
gsettings set org.gnome.desktop.interface cursor-theme "vimix"
gsettings set org.gnome.desktop.interface cursor-size 32

killall -w picom
picom -b
